// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Protocol.proto

/*
Package Protocol is a generated protocol buffer package.

It is generated from these files:
	Protocol.proto

It has these top-level messages:
	User
	Address
	Connection
*/
package Protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id              int32         `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	FirstName       string        `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName        string        `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Gender          string        `protobuf:"bytes,4,opt,name=gender" json:"gender,omitempty"`
	Wants           []string      `protobuf:"bytes,5,rep,name=wants" json:"wants,omitempty"`
	Haves           []string      `protobuf:"bytes,6,rep,name=haves" json:"haves,omitempty"`
	BusinessAddress *Address      `protobuf:"bytes,7,opt,name=business_address,json=businessAddress" json:"business_address,omitempty"`
	PrimaryCompany  *User_Company `protobuf:"bytes,8,opt,name=primary_company,json=primaryCompany" json:"primary_company,omitempty"`
	Languages       []string      `protobuf:"bytes,9,rep,name=languages" json:"languages,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetWants() []string {
	if m != nil {
		return m.Wants
	}
	return nil
}

func (m *User) GetHaves() []string {
	if m != nil {
		return m.Haves
	}
	return nil
}

func (m *User) GetBusinessAddress() *Address {
	if m != nil {
		return m.BusinessAddress
	}
	return nil
}

func (m *User) GetPrimaryCompany() *User_Company {
	if m != nil {
		return m.PrimaryCompany
	}
	return nil
}

func (m *User) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

type User_Company struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *User_Company) Reset()                    { *m = User_Company{} }
func (m *User_Company) String() string            { return proto.CompactTextString(m) }
func (*User_Company) ProtoMessage()               {}
func (*User_Company) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *User_Company) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *User_Company) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Address struct {
	Country string `protobuf:"bytes,1,opt,name=country" json:"country,omitempty"`
	Zipcode string `protobuf:"bytes,2,opt,name=zipcode" json:"zipcode,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	Street  string `protobuf:"bytes,4,opt,name=street" json:"street,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

type Connection struct {
	A int32 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *Connection) Reset()                    { *m = Connection{} }
func (m *Connection) String() string            { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()               {}
func (*Connection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Connection) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Connection) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*User_Company)(nil), "User.Company")
	proto.RegisterType((*Address)(nil), "Address")
	proto.RegisterType((*Connection)(nil), "Connection")
}

func init() { proto.RegisterFile("Protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x69, 0xb7, 0xae, 0xeb, 0x55, 0x37, 0x09, 0x43, 0x82, 0x7f, 0xa0, 0xec, 0xa9, 0x4f,
	0x7d, 0x70, 0xe0, 0xbb, 0xec, 0x5d, 0x24, 0xe0, 0xf3, 0x48, 0xdb, 0xeb, 0x0c, 0xac, 0x49, 0x49,
	0x32, 0xa5, 0x7e, 0x50, 0x3f, 0x8f, 0x24, 0x4d, 0xd0, 0xb7, 0xfb, 0x3b, 0xe7, 0xde, 0x90, 0x7b,
	0x2e, 0xac, 0x5e, 0xb5, 0xb2, 0xaa, 0x55, 0xa7, 0x7a, 0x70, 0xc5, 0xf6, 0x27, 0x85, 0xf9, 0x9b,
	0x41, 0x4d, 0x56, 0x90, 0x8a, 0x8e, 0x26, 0x65, 0x52, 0x65, 0x2c, 0x15, 0x1d, 0x79, 0x00, 0x78,
	0x17, 0xda, 0xd8, 0x83, 0xe4, 0x3d, 0xd2, 0xb4, 0x4c, 0xaa, 0x82, 0x15, 0x5e, 0x79, 0xe1, 0x3d,
	0x92, 0x3b, 0x28, 0x4e, 0x3c, 0xba, 0x33, 0xef, 0x2e, 0x9d, 0xe0, 0xcd, 0x1b, 0x58, 0x1c, 0x51,
	0x76, 0xa8, 0xe9, 0xdc, 0x3b, 0x81, 0xc8, 0x06, 0xb2, 0x2f, 0x2e, 0xad, 0xa1, 0x59, 0x39, 0xab,
	0x0a, 0x36, 0x81, 0x53, 0x3f, 0xf8, 0x27, 0x1a, 0xba, 0x98, 0x54, 0x0f, 0x64, 0x07, 0xd7, 0xcd,
	0xd9, 0x08, 0x89, 0xc6, 0x1c, 0x78, 0xd7, 0x69, 0x34, 0x86, 0xe6, 0x65, 0x52, 0x5d, 0x3c, 0x2e,
	0xeb, 0xe7, 0x89, 0xd9, 0x3a, 0x76, 0x04, 0x81, 0x3c, 0xc1, 0x7a, 0xd0, 0xa2, 0xe7, 0x7a, 0x3c,
	0xb4, 0xaa, 0x1f, 0xb8, 0x1c, 0xe9, 0xd2, 0xcf, 0x5c, 0xd5, 0x6e, 0xc9, 0x7a, 0x3f, 0x89, 0x6c,
	0x15, 0xba, 0x02, 0x93, 0x7b, 0xb7, 0x8d, 0x3c, 0x9e, 0xf9, 0x11, 0x0d, 0x2d, 0xfc, 0x37, 0xfe,
	0x84, 0xdb, 0x1d, 0xe4, 0xb1, 0x71, 0x03, 0x99, 0x15, 0xf6, 0x84, 0x3e, 0xa8, 0x82, 0x4d, 0x40,
	0x08, 0xcc, 0xff, 0xa5, 0xe4, 0xeb, 0xad, 0x80, 0x3c, 0xfe, 0x8a, 0x42, 0xde, 0xaa, 0xb3, 0xb4,
	0x7a, 0x0c, 0x63, 0x11, 0x9d, 0xf3, 0x2d, 0x86, 0x56, 0x75, 0x71, 0x36, 0xa2, 0x7b, 0xb2, 0x15,
	0x76, 0x0c, 0xd1, 0xfa, 0xda, 0xc5, 0x6a, 0xac, 0x46, 0xb4, 0x31, 0xd6, 0x89, 0xb6, 0x15, 0xc0,
	0x5e, 0x49, 0x89, 0xad, 0x15, 0x4a, 0x92, 0x4b, 0x48, 0x78, 0xb8, 0x63, 0xc2, 0x1d, 0x35, 0xfe,
	0xed, 0x8c, 0x25, 0x4d, 0xb3, 0xf0, 0x47, 0xdf, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x16, 0x52,
	0xcc, 0xe5, 0x06, 0x02, 0x00, 0x00,
}
